version: '2'

services:

  cassandra:
    image: bitnami/cassandra:3
    volumes:
      - cassandra_data:/bitnami
      - ./db-schema:/docker-entrypoint-init.d/
    ports:
    - '7000:7000'
    - '9042:9042'

    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

volumes:
  cassandra_data:
    driver: local